fix: Fix release-please manifest file name
release-please was complaining about not finding the manifest in CI:

Error: release-please failed: base (grafana/synthetic-monitoring-api-go-client):
Missing required manifest versions: .github/release-please/.release-please-manifest.json

Although it was still incrementing the version correctly.